services:
  piper_ros2:
    image: piper-elevator:humble
    build:
      context: .
      dockerfile: docker/Dockerfile
      network: host
      args:
        HTTP_PROXY: ${HTTP_PROXY:-}
        HTTPS_PROXY: ${HTTPS_PROXY:-}
        NO_PROXY: ${NO_PROXY:-localhost,127.0.0.1,::1}
    network_mode: host
    ipc: host
    gpus: all
    privileged: true
    environment:
      DISPLAY: ${DISPLAY:-:0}
      QT_X11_NO_MITSHM: "1"
      QT_OPENGL: software
      QT_XCB_GL_INTEGRATION: none
      LIBGL_ALWAYS_SOFTWARE: "1"
      XDG_RUNTIME_DIR: /tmp/runtime-root
      ROS_DOMAIN_ID: ${ROS_DOMAIN_ID:-0}
      HTTP_PROXY: ${HTTP_PROXY:-}
      HTTPS_PROXY: ${HTTPS_PROXY:-}
      NO_PROXY: ${NO_PROXY:-localhost,127.0.0.1,::1}
    volumes:
      - ./ros2_ws:/workspace/ros2_ws
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev:/dev
    working_dir: /workspace/ros2_ws
    stdin_open: true
    tty: true
    command: bash
